management:
    endpoint:
        beans:
            enabled: true
        health:
            enabled: true
        info:
            enabled: true
        mappings:
            enabled: true
        metrics:
            enabled: true
    endpoints:
        enabled-by-default: false
        jmx:
            exposure:
                include: beans,caches,health,info,mappings,metrics
        web:
            exposure:
                include: beans,caches,health,info,mappings,metrics
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: stateproject
        url: jdbc:postgresql://localhost:5432/stateproject
        username: stateproject
    jmx:
        enabled: true
    jpa:
        database: POSTGRESQL
        hibernate.ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: $PORT

security:
    firebase-props:
        database-url: ${FIREBASE_DATABASE}
        enable-strict-server-session: false
        enable-check-session-revoked: false
        enable-logout-everywhere: false
        session-expiry-in-days: 5
    cookie-props:
        max-age-in-minutes: 7200
        http-only: true
        secure: true
        domain: ${DOMAIN}
        path: /
    allow-credentials: true
    allowed-origins:
        - https://${DOMAIN}
        - http://localhost:3000
    allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
    allowed-headers:
        - Authorization
        - Origin
        - Content-Type
        - Accept
        - Accept-Encoding
        - Accept-Language
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Headers
        - Access-Control-Request-Method
        - X-Requested-With
        - X-Auth-Token
        - X-Xsrf-Token
        - Cache-Control
        - Id-Token
    allowed-public-apis:
        - /favicon.ico
        - /session/login
        - /api/**
    exposed-headers:
        - X-Xsrf-Token